version: '3'

services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pott
      
    command: mysqld --lower_case_table_names=1
    

  pott:
    image: pott/pottv3:part3
    entrypoint: ["java", "-jar", "planet_of_the_tapes-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pott
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create
    ports:
      - 8443:8443
