version: '3.3'

services: 

  db:
    image: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: pott
    
  spring:
    image: pott/pott
    restart: always
    depends_on:
      - db
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pott
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update